import React, { useRef } from 'react';
import { Download, Mail, Printer } from 'lucide-react';
import type { PayrollRecord } from '../hooks/usePayroll';
import { DEFAULT_SETTINGS, calculateSalary, type PayrollSettingsData } from '../hooks/usePayrollSettings';

// ─────────────────────────────────────────────────────────
// PayslipData — the shape passed to the template
// ─────────────────────────────────────────────────────────
export interface PayslipData {
  companyName: string;
  companyAddress: string;
  companyEmail: string;
  companyPhone: string;
  // Employee info
  employeeId: string;
  employeeName: string;
  designation: string;
  department: string;
  dateOfJoining: string;
  uan: string;
  pfNo: string;
  bank: string;
  accountNo: string;
  ifscCode: string;
  // Period
  date: string;
  payPeriod: string;
  // Wages summary
  grossWages: number;
  totalWorkingDays: number;
  lopDays: number;
  paidDays: number;
  // Earnings breakdown
  earnings: {
    basic: number;
    hra: number;
    conveyance: number;
    medical: number;
    otherAllowances: number;
  };
  // Deductions breakdown
  deductions: {
    epf: number;          // pf_employee + pf_employer (combined display)
    esi: number;          // esi_employee
    profTax: number;
    lopDeduction: number;
  };
}

// ─────────────────────────────────────────────────────────
// Helper: map PayrollRecord + settings → PayslipData
// ─────────────────────────────────────────────────────────
export const buildPayslipData = (
  record: PayrollRecord,
  payPeriod: string,
  settings?: PayrollSettingsData
): PayslipData => {
  const p = record.profile as any;
  const gross = record.gross_salary || 0;
  const effectiveSettings = settings || DEFAULT_SETTINGS;
  const daysInMonth = record.working_days || 30;

  // Always recompute breakdown from gross using settings.
  // This ensures payslips are always correct regardless of what's stored.
  const bd = gross > 0
    ? calculateSalary(gross, effectiveSettings, record.total_lop_days || 0, daysInMonth)
    : null;

  // If the record has stored non-zero breakdown (generated by new engine),
  // prefer stored values for EPF/ESI/PT as they reflect actual stored calculations.
  const hasStoredBreakdown = (record.pf_employee || 0) > 0 || (record.professional_tax || 0) > 0;

  const earnings = {
    basic: bd ? bd.basic : 0,
    hra: bd ? bd.hra : 0,
    conveyance: bd ? bd.conveyance : 0,
    medical: bd ? bd.medical : 0,
    otherAllowances: bd ? bd.other_allowances : 0,
  };
  const deductions = {
    epf: hasStoredBreakdown
      ? (record.pf_employee || 0) + (record.pf_employer || 0)
      : (bd ? bd.epf_display : 0),
    esi: hasStoredBreakdown ? (record.esi_employee || 0) : (bd ? bd.esi_employee : 0),
    profTax: hasStoredBreakdown ? (record.professional_tax || 0) : (bd ? bd.professional_tax : 0),
    lopDeduction: record.lop_deduction_amount || (bd ? bd.lop_deduction : 0),
  };

  return {
    companyName: 'Versovate Labs Pvt Ltd',
    companyAddress: 'Dhanalakshmi Complex, 392, 7th Cross Rd, above lifecare medicals, Mico Layout, BTM 2nd Stage, BTM Layout, Bengaluru, Karnataka 560076',
    companyEmail: 'info@versovate.com',
    companyPhone: '+91 80-35874073',
    employeeId: p?.custom_id || '—',
    employeeName: (p?.full_name || '—').toUpperCase(),
    designation: (p?.job_title || p?.designation || '—').toUpperCase(),
    department: p?.department || '—',
    dateOfJoining: p?.join_date || '—',
    uan: p?.uan || '—',
    pfNo: p?.pf_number || '—',
    bank: p?.bank_name || '—',
    accountNo: p?.bank_account_number || '—',
    ifscCode: p?.bank_ifsc || '—',
    date: new Date().toLocaleDateString('en-IN'),
    payPeriod,
    grossWages: gross,
    totalWorkingDays: daysInMonth,
    lopDays: record.total_lop_days || 0,
    paidDays: daysInMonth - (record.total_lop_days || 0),
    earnings,
    deductions,
  };
};

export const defaultPayslipData: PayslipData = {
  companyName: 'Versovate Labs Pvt Ltd',
  companyAddress: 'Dhanalakshmi Complex, 392, 7th Cross Rd, Bengaluru, Karnataka 560076',
  companyEmail: 'info@versovate.com',
  companyPhone: '+91 80-35874073',
  employeeId: 'VL01',
  employeeName: 'SADDAM HUSSAIN',
  designation: 'CHIEF EXECUTIVE OFFICER',
  department: '—',
  dateOfJoining: '23/09/2025',
  uan: '101196616437',
  pfNo: 'PYBOM3711595000',
  bank: 'HDFC BANK',
  accountNo: '50100859169212',
  ifscCode: 'HDFC0006429',
  date: '10/02/2026',
  payPeriod: 'January 2026',
  grossWages: 104800,
  totalWorkingDays: 31,
  lopDays: 0,
  paidDays: 31,
  earnings: {
    basic: 52350,
    hra: 20000,
    conveyance: 5000,
    medical: 5000,
    otherAllowances: 22450,
  },
  deductions: {
    epf: 3600,
    esi: 0,
    profTax: 200,
    lopDeduction: 0,
  },
};

// ─────────────────────────────────────────────────────────
// Component
// ─────────────────────────────────────────────────────────
const PayslipTemplate: React.FC<{ data?: PayslipData; hideActions?: boolean }> = ({
  data = defaultPayslipData,
  hideActions = false,
}) => {
  const printRef = useRef<HTMLDivElement>(null);

  const totalEarnings = data.earnings.basic + data.earnings.hra + data.earnings.conveyance +
    data.earnings.medical + data.earnings.otherAllowances;

  const totalDeductions = data.deductions.epf + data.deductions.esi +
    data.deductions.profTax + data.deductions.lopDeduction;

  const netSalary = Math.max(0, totalEarnings - totalDeductions);
  const fmt = (n: number) => `₹${Number(n || 0).toLocaleString('en-IN')}`;

  return (
    <div className="payslip-container">
      {!hideActions && (
        <div className="payslip-actions no-print">
          <button className="action-btn" onClick={() => window.print()}>
            <Printer size={18} /> Print
          </button>
          <button className="action-btn primary">
            <Download size={18} /> Download
          </button>
          <button className="action-btn">
            <Mail size={18} /> Email
          </button>
        </div>
      )}

      <div className="payslip-paper" ref={printRef}>
        {/* Purple header */}
        <div className="payslip-branding-header">
          <div className="header-meta">
            <h2>Payslip</h2>
            <p>Date : {data.date}</p>
            <p>Pay Period : {data.payPeriod}</p>
          </div>
          <div className="header-logo">
            <img src="/assets/white_logo.png" alt="Logo" className="v-logo-img" />
          </div>
        </div>

        <div className="payslip-body">
          {/* Company + Employee info */}
          <div className="info-grid">
            <div className="company-info-panel">
              <span className="info-label-muted">Company Name</span>
              <h3 className="company-title">{data.companyName}</h3>
              <p className="company-addr">{data.companyAddress}</p>
              <div className="contact-row"><span>Email</span><a href={`mailto:${data.companyEmail}`}>{data.companyEmail}</a></div>
              <div className="contact-row"><span>Phone</span><span>{data.companyPhone}</span></div>
            </div>
            <div className="employee-info-panel">
              <div className="emp-detail-row"><span>EMPLOYEE ID</span><span>: {data.employeeId}</span></div>
              <div className="emp-detail-row"><span>EMPLOYEE NAME</span><span className="text-bold">: {data.employeeName}</span></div>
              <div className="emp-detail-row"><span>DESIGNATION</span><span>: {data.designation}</span></div>
              <div className="emp-detail-row"><span>DEPARTMENT</span><span>: {data.department}</span></div>
              <div className="emp-detail-row"><span>DATE OF JOINING</span><span>: {data.dateOfJoining}</span></div>
              <div className="emp-detail-row"><span>UAN</span><span>: {data.uan}</span></div>
              <div className="emp-detail-row"><span>PF NO</span><span>: {data.pfNo}</span></div>
              <div className="emp-detail-row"><span>BANK</span><span>: {data.bank}</span></div>
              <div className="emp-detail-row"><span>ACCOUNT NO</span><span>: {data.accountNo}</span></div>
              <div className="emp-detail-row"><span>IFSC CODE</span><span>: {data.ifscCode}</span></div>
            </div>
          </div>

          {/* Wages summary */}
          <table className="wages-summary-table">
            <tbody>
              <tr>
                <td className="bg-gray bold">Gross Wages</td>
                <td className="bold text-right" style={{ width: '140px' }}>{fmt(data.grossWages)}</td>
                <td colSpan={2}></td>
              </tr>
              <tr>
                <td className="bg-gray bold">Total Working Days</td>
                <td className="text-right">{data.totalWorkingDays}</td>
                <td className="bg-gray bold">Leaves</td>
                <td className="text-right">0</td>
              </tr>
              <tr>
                <td className="bg-gray bold">LOP Days</td>
                <td className="text-right">{data.lopDays}</td>
                <td className="bg-gray bold">Paid Days</td>
                <td className="text-right">{data.paidDays}</td>
              </tr>
            </tbody>
          </table>

          {/* Earnings & Deductions */}
          <table className="earnings-deductions-table">
            <thead>
              <tr className="bg-light-blue">
                <th className="text-left text-primary">Earnings</th>
                <th className="text-right" style={{ width: '120px' }}></th>
                <th className="text-left text-primary border-left">Deductions</th>
                <th className="text-right" style={{ width: '120px' }}></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="bold">Basic</td>
                <td className="text-right">{fmt(data.earnings.basic)}</td>
                <td className="border-left">EPF</td>
                <td className="text-right">{fmt(data.deductions.epf)}</td>
              </tr>
              <tr>
                <td className="bold">HRA</td>
                <td className="text-right">{fmt(data.earnings.hra)}</td>
                <td className="border-left">ESI</td>
                <td className="text-right">{fmt(data.deductions.esi)}</td>
              </tr>
              <tr>
                <td className="bold">Conveyance Allowance</td>
                <td className="text-right">{fmt(data.earnings.conveyance)}</td>
                <td className="border-left">Professional Tax</td>
                <td className="text-right">{fmt(data.deductions.profTax)}</td>
              </tr>
              <tr>
                <td className="bold">Medical Allowance</td>
                <td className="text-right">{fmt(data.earnings.medical)}</td>
                <td className="border-left">{data.deductions.lopDeduction > 0 ? 'Loss of Pay' : ''}</td>
                <td className="text-right">{data.deductions.lopDeduction > 0 ? fmt(data.deductions.lopDeduction) : ''}</td>
              </tr>
              <tr>
                <td className="bold">Other Allowances</td>
                <td className="text-right">{fmt(data.earnings.otherAllowances)}</td>
                <td className="border-left"></td>
                <td className="text-right"></td>
              </tr>
              <tr className="border-top-thick">
                <td className="bold">Total Earnings</td>
                <td className="bold text-right">{fmt(totalEarnings)}</td>
                <td className="bold border-left">Total Deductions</td>
                <td className="bold text-right">{fmt(totalDeductions)}</td>
              </tr>
              <tr>
                <td colSpan={2} className="border-none"></td>
                <td className="bold net-salary-label">Net Salary</td>
                <td className="bold net-salary-final text-right">{fmt(netSalary)}</td>
              </tr>
            </tbody>
          </table>

          {/* Net salary banner */}
          <div className="net-salary-banner">
            Net Salary {fmt(netSalary)}/-
          </div>
        </div>
      </div>

      <style>{`
                .payslip-container { padding: 40px; background: var(--bg-main); display: flex; flex-direction: column; align-items: center; }
                .payslip-actions { width: 900px; display: flex; justify-content: flex-end; gap: 12px; margin-bottom: 24px; }
                .action-btn { padding: 10px 20px; border-radius: 8px; border: 1px solid var(--border-color); background: var(--bg-card); cursor: pointer; display: flex; align-items: center; gap: 8px; font-weight: 600; color: var(--text-secondary); }
                .action-btn.primary { background: var(--color-primary); color: #fff; border: none; }
                .payslip-paper { width: 900px; background: white; color: #1a1a1a; font-family: 'Inter', sans-serif; box-shadow: 0 10px 30px rgba(0,0,0,0.1); overflow: hidden; padding-bottom: 60px; }
                .payslip-branding-header { background: #6232FF; color: white; padding: 40px 60px; display: flex; justify-content: space-between; align-items: center; }
                .header-meta h2 { font-size: 28px; font-weight: 700; margin-bottom: 12px; color: white; }
                .header-meta p { font-size: 14px; opacity: 0.9; margin: 2px 0; color: white; }
                .header-logo { display: flex; align-items: center; }
                .v-logo-img { height: 70px; object-fit: contain; }
                .payslip-body { padding: 40px 60px; }
                .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 60px; margin-bottom: 40px; }
                .info-label-muted { font-size: 12px; font-weight: 700; color: #6232FF; text-transform: uppercase; display: block; margin-bottom: 10px; }
                .company-title { font-size: 20px; font-weight: 700; color: #1a1a1a; margin-bottom: 15px; }
                .company-addr { font-size: 13px; color: #666; line-height: 1.6; margin-bottom: 15px; }
                .contact-row { display: flex; gap: 15px; font-size: 13px; color: #666; margin-bottom: 5px; }
                .contact-row span:first-child { width: 45px; font-weight: 600; }
                .contact-row a { color: #6232FF; text-decoration: none; }
                .employee-info-panel { display: flex; flex-direction: column; gap: 5px; }
                .emp-detail-row { display: grid; grid-template-columns: 160px 1fr; font-size: 12px; font-weight: 600; color: #1a1a1a; padding: 2px 0; }
                .emp-detail-row span:first-child { font-weight: 500; color: #555; }
                .text-bold { font-weight: 800; }
                table { width: 100%; border-collapse: collapse; margin-bottom: 0; table-layout: fixed; }
                th, td { border: 1px solid #ddd; padding: 12px 15px; font-size: 13px; overflow: hidden; text-overflow: ellipsis; }
                .bg-gray { background: #f9f9f9; }
                .bg-light-blue { background: #f8fbff; }
                .bold { font-weight: 700; }
                .text-right { text-align: right; }
                .text-left { text-align: left; }
                .text-primary { color: #6232FF; font-weight: 800; }
                .wages-summary-table { margin-bottom: -1px; }
                .earnings-deductions-table { margin-top: 30px; }
                .border-left { border-left: 2px solid #e0e0e0; }
                .border-none { border: none !important; background: transparent; }
                .border-top-thick td { border-top: 2px solid #ccc !important; background: #fafafa; }
                .net-salary-label { background: #f3f0ff; text-align: right; font-size: 14px; color: #6232FF; font-weight: 700; }
                .net-salary-final { font-size: 18px; color: #6232FF; font-weight: 900; background: #f3f0ff; }
                .net-salary-banner { margin-top: 40px; background: #6232FF; color: white; padding: 18px 30px; font-size: 20px; font-weight: 700; width: fit-content; border-radius: 4px; }
                @media print {
                  .no-print { display: none !important; }
                  .payslip-container { padding: 0; background: white; }
                  .payslip-paper { box-shadow: none; border: none; width: 100%; }
                  body { background: white; }
                }
            `}</style>
    </div>
  );
};

export default PayslipTemplate;
